[package]
name = "superfilter_macro"
version = "0.1.0"
authors = ["Stefan Kaufhold <cere@fastmail.fm>"]

[dependencies]
syn = "0.11"
quote = "0.3"

[lib]
name = "superfilter_macro"
path = "src/lib.rs"
proc-macro = true
